### ISSUE TITLE
Exits with "list index out of range"

### ISSUE THREAD

**Issue by MKRhere** [itzmeanjan/chanalyze#11]
![image](https://user-images.githubusercontent.com/19621208/100972580-0828f800-355f-11eb-8940-14394b92382d.png)

I tried with a few different exports of different sizes, I get the same error. No idea where to begin debugging.

**Comment by itzmeanjan** [comment]
Can't even ask you for chat data. Let me try with one sample exported chat data.

**Comment by MKRhere** [comment]
I can share sample data that caused the issue. Is there a way I can share privately?

**Comment by itzmeanjan** [comment]
Yes you can. Please email me chat file at anjanroy@yandex.com

**Comment by MKRhere** [comment]
_(take your time to check it out, leaving this comment for reference that I have sent the email)_

**Comment by itzmeanjan** [comment]
Sorry for delayed response, I've received chat file & I'm looking into it. I'll respond here & also via email, whenever I'm done with it.

@MKRhere

**Comment by itzmeanjan** [comment]
Hello @MKRhere , I've detected the issue and fixed it, now it should work smoothly for your chat file. 

Please check: https://github.com/itzmeanjan/chanalyze/releases/tag/v0.3.9

Actually `chanalyze` didn't consider chat timestamps in 24-hours format previously, which was reason behind its failure.

Thanks for helping in improving `chanalyze` :wink:

**Comment by MKRhere** [comment]
Seems to work now, @itzmeanjan :) Thanks!

**Comment by veudal** [comment]
I still got the exact same issue in the latest version.
![image](https://github.com/itzmeanjan/chanalyze/assets/62218506/dc755fed-c3ac-4bb3-92df-92d913f04d3d)

I tried different files but same error on each one and would greatly appreciate help. Here is the content of an example file which also throws the same error:

12.01.2024 20:17 - User: hi
