### ISSUE TITLE
Word cloud analyser does not seem to understand contractions

### ISSUE THREAD

**Issue by MKRhere** [itzmeanjan/chanalyze#12]
While not a critical issue, I found that in all examples I tried, one of the most common words used was "ll" according to the word cloud, owing to the fact that contractions that use apostrophes, such as "I'll", "we'll", "he'll", etc seem to be broken down into two words, such as "I ll", "we ll", and "he ll".

While fixing this for English words is fairly straightforward, I'm not sure what the ideal generic solution would be. I don't actively need a fix, just letting you know it is an issue.

**Comment by itzmeanjan** [comment]
Yes that's one issue, I'll fix it. Thanks for reporting it @MKRhere

**Comment by itzmeanjan** [comment]
This project is not being maintained anymore, hence I'm closing this issue.
